language: go

go:
  - 1.12.x

before_script:
  - go get ./...

script:
  - go build -ldflags "-s -w" -o tgmsg

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  skip_cleanup: true
  file: tgmsg
  on:
    tags: true
