language: go

go:
  - 1.x

before_script:
  - go vet ./...

script:
  - go build -o tgmsg

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  skip_cleanup: true
  file: tgmsg
  on:
    tags: true
